### ISSUE TITLE
refactorizacion y otros....

### ISSUE THREAD

**Issue by bilbobolsoncerrado** [Ser090/RetoG2DAM#57]
En ImplementacionBD
1.- modificarReceta: Código repetido
2.- No es de EDE: ¿Por qué a veces closeConnection está dentro del try y otras no?
3.- No es de EDE: En altaIngrediente
while (rs.next()) {
				codigo = rs.getInt("CODIGO");
			}
¿Para qué sirve esto?
En VentanaBuscarREceta
.- formatoTabla: mejorar nombres de variables, todas en el mismo idioma, nombre de variable "c" cambiar

**Comment by Urkopf** [comment]
1.- Podemos fusionar altaReceta y modificarReceta teniendo en cuenta si inicialmente el codigo de la receta es null o no, para diferenciar alta de modificar en el mismo metodo.
2.- Ordenar codigo de Implementacion , los closeConnection yo los pondria en un finally de los trycatch para asegurar que cierran conexion
3.- El rs en principio hay que mover el cursor de datos al menos una vez para poder acceder al codigo que nos devuelve al query. Es neceario consultar ese codigo porq inicialmente no hay codigo en un nuevo ingrediente hasta que se inserta y la BD asigna un codigo autoincremental. Ese codigo nos hacer falta para agregarlo al resto de tablas que relacionan el ingrediente.
4.- Hay que ordenar y renombrar muchas variables en la mayoria de las ventanas.

**Comment by bilbobolsoncerrado** [comment]
3.- No es de EDE: En altaIngrediente
while (rs.next()) {
codigo = rs.getInt("CODIGO");
}
Solo queria advertir de que en este bucle no se está haciendo nada con el contenido de codigo.
 creo que con un select MAX() estaría mejor para obtener el valor máximo del AUTOINCREMENTAL.
Imagina que la fila tiene 180000 filas... qué desperdicio!! un while para llegar a la última...

**Comment by Urkopf** [comment]
En este caso el resultset solo tiene 1 código una fila porque es el resultado de una función de la BD tenemos una función que nos devuelve el código de la receta que acaba de dar de alta pero comprendo lo que me comentas, ya miramos a ver.
